name: test-infraset-${uid}

sqs:
 test-queue-${uid}:
   attr:
     - timeout=60

lambda:
  test-lambda-${uid}:
    entrypoint: ${account}.dkr.ecr.${region}.amazonaws.com/test-container@${digest}
    attr:
      - concurrency=0
      - memory=128
      - timeout=60
    policy:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaSQSQueueExecutionRole
    trigger:
      - type: sqs
        attr:
          - test-queue-${uid}
          - batch=1
          - window=1
